force run

diff --git a/.github/workflows/alp-db-svc-test.yml b/.github/workflows/alp-db-svc-test.yml
--- a/.github/workflows/alp-db-svc-test.yml
+++ b/.github/workflows/alp-db-svc-test.yml
@@ -81,44 +81,44 @@ jobs:
           ls "${HANA__DRIVER_CLASS_PATH}"
           ls "${POSTGRES__DRIVER_CLASS_PATH}"
 
-      - uses: actions/checkout@v4
-        name: sameBranch checkout (OverrideRepo)
-        id: sameBranch-checkout
-        continue-on-error: true
-        with:
-          repository:  ${{ vars.OVERRIDE_REPO }}
-          token: ${{ secrets.CI_PAT }}
-          path: 'tmp'
-          sparse-checkout: 'alp-data-node-override'
-          sparse-checkout-cone-mode: false
-          ref: ${{ env.BRANCH_NAME }}
+      # - uses: actions/checkout@v4
+      #   name: sameBranch checkout (OverrideRepo)
+      #   id: sameBranch-checkout
+      #   continue-on-error: true
+      #   with:
+      #     repository:  ${{ vars.OVERRIDE_REPO }}
+      #     token: ${{ secrets.CI_PAT }}
+      #     path: 'tmp'
+      #     sparse-checkout: 'alp-data-node-override'
+      #     sparse-checkout-cone-mode: false
+      #     ref: ${{ env.BRANCH_NAME }}
 
-      - shell: bash
-        name: sameBranch checkout test
-        id: sameBranch-checkout-test
-        run: |
-          ls -lhtr tmp
-          [ -d tmp/alp-data-node-override ] || echo OVERRIDE_DEVELOP_BRANCH=true | tee -a "$GITHUB_OUTPUT"
+      # - shell: bash
+      #   name: sameBranch checkout test
+      #   id: sameBranch-checkout-test
+      #   run: |
+      #     ls -lhtr tmp
+      #     [ -d tmp/alp-data-node-override ] || echo OVERRIDE_DEVELOP_BRANCH=true | tee -a "$GITHUB_OUTPUT"
 
-      - uses: actions/checkout@v4
-        name: develop branch checkout (sameBranch checkout fails)
-        if: steps.sameBranch-checkout-test.outputs.OVERRIDE_DEVELOP_BRANCH == 'True' 
-        with:
-          repository:  ${{ vars.OVERRIDE_REPO }}
-          token: ${{ secrets.CI_PAT }}
-          path: 'tmp'
-          sparse-checkout: 'alp-data-node-override'
-          sparse-checkout-cone-mode: false
-          ref: develop
+      # - uses: actions/checkout@v4
+      #   name: develop branch checkout (sameBranch checkout fails)
+      #   if: steps.sameBranch-checkout-test.outputs.OVERRIDE_DEVELOP_BRANCH == 'True' 
+      #   with:
+      #     repository:  ${{ vars.OVERRIDE_REPO }}
+      #     token: ${{ secrets.CI_PAT }}
+      #     path: 'tmp'
+      #     sparse-checkout: 'alp-data-node-override'
+      #     sparse-checkout-cone-mode: false
+      #     ref: develop
 
-      - shell: bash
-        name: merge files from override
-        id: merge_files_from_override
-        run: |
-          ls -l tmp/alp-data-node-override
-          cp -prnl ./tmp/alp-data-node-override/* .
-          ls -l ./services/alp-db-svc/db/drivers
-          ln -s tmp/alp-data-node-override alp-data-node-override
+      # - shell: bash
+      #   name: merge files from override
+      #   id: merge_files_from_override
+      #   run: |
+      #     ls -l tmp/alp-data-node-override
+      #     cp -prnl ./tmp/alp-data-node-override/* .
+      #     ls -l ./services/alp-db-svc/db/drivers
+      #     ln -s tmp/alp-data-node-override alp-data-node-override
 
       - shell: bash
         # Give an id to the step, so we can reference it later
@@ -140,12 +140,12 @@ jobs:
           echo "Does db-svc have changes: $hasDiff"
 
       - uses: actions/setup-node@v3
-        if: github.ref_name == 'develop' || steps.check_file_changed.outputs.has_dbsvc_changed == 'True'
+        if: github.ref_name == 'develop' # || steps.check_file_changed.outputs.has_dbsvc_changed == 'True'
         with:
           node-version: "18.14.0"
 
       - name: Build Project (DB-SVC)
-        if: github.ref_name == 'develop' || steps.check_file_changed.outputs.has_dbsvc_changed == 'True'
+        if: github.ref_name == 'develop' # || steps.check_file_changed.outputs.has_dbsvc_changed == 'True'
         run: |
           # Build alp-libs dependencies for alp-db-svc
           yarn install --frozen-lockfile
@@ -157,7 +157,7 @@ jobs:
           yarn compile
 
       - name: Setup Test DB (postgres)
-        if: github.ref_name == 'develop' || steps.check_file_changed.outputs.has_dbsvc_changed == 'True'
+        if: github.ref_name == 'develop' # || steps.check_file_changed.outputs.has_dbsvc_changed == 'True'
         working-directory: ./services/alp-db-svc
         run: |
           # Create cdmvocab and cdmdefault schema for db-svc integration tests
@@ -168,13 +168,13 @@ jobs:
       - name: Run integration tests for DB-SVC POSTGRES
         working-directory: ./services/alp-db-svc
         # run only if files in 'has_dbsvc_changed' is set to 'True'
-        if: github.ref_name == 'develop' || steps.check_file_changed.outputs.has_dbsvc_changed == 'True'
+        if: github.ref_name == 'develop' # || steps.check_file_changed.outputs.has_dbsvc_changed == 'True'
         run: |
           npm run pgtest
 
       - name: Run integration tests for DB-SVC HANA
         working-directory: ./services/alp-db-svc
         # run only if files in 'has_dbsvc_changed' is set to 'True'
-        if: github.ref_name == 'develop' || steps.check_file_changed.outputs.has_dbsvc_changed == 'True'
+        if: github.ref_name == 'develop' # || steps.check_file_changed.outputs.has_dbsvc_changed == 'True'
         run: |
           npm run test
